### ISSUE TITLE
Use Weave.jl and Literate.jl Build Reproducible Jupyter Notebooks

### ISSUE THREAD

**Issue by TheCedarPrince** [TheCedarPrince/LinAlgTuts.jl#4]
From a discussion with @miguelraz, you can combine Weave.jl with Literate.jl to create reproducible notebooks. From there, one can set-up a CI command that creates a Jupyter notebook from the end Julia code. This can encourage ease of working with PRs and filing issues.

Thus the break down for this issue is:

- [x] Determine how [Weave.jl](https://github.com/JunoLab/Weave.jl) works
- [x] Determine how [Literate.jl](https://github.com/fredrikekre/Literate.jl) works
- [x] See how to combine these two ideas together to create a woven .jl file
- [x] Convert the woven file to a Jupyter notebook

**Comment by TheCedarPrince** [comment]
This might be worthwhile to look at https://github.com/baggepinnen/LiterateWeave.jl

**Comment by miguelraz** [comment]
You can probably base your workflow around something like 
https://github.com/SciML/DiffEqTutorials.jl

**Comment by TheCedarPrince** [comment]
This is exactly what I want to do! `Weave.jl` works perfectly for what I want. `Literate.jl` seems more focused on documentation of codebases and not exactly for writing tutorials and the like.

**Comment by TheCedarPrince** [comment]
Thanks for the advice @miguelraz , I like their set-up for the different tutorials they have so everyone could check it out. I will replicate that here.
